### ISSUE TITLE
It doesn't compile on Slackware

### ISSUE THREAD

**Issue by bogdanr** [sboli/twmn#64]
This is the error I receive when I try to compile:
```C
main.cpp:17:38: error: ‘QMessageLogContext’ does not name a type
 void logOutput(QtMsgType type, const QMessageLogContext &context, const QString &msg)
                                      ^
main.cpp: In function ‘int main(int, char**)’:
main.cpp:47:37: error: ‘qInstallMessageHandler’ was not declared in this scope
     qInstallMessageHandler(logOutput);
                                     ^
make[1]: *** [Makefile:263: main.o] Error 1
make: *** [Makefile:40: sub-twmnd-make_default] Error 2
```

**Comment by piknik** [comment]
It doesn't compile in Ubuntu 16.04 either. Same error.

**Comment by shuforov** [comment]
I got same error on Ubuntu 16.04.

**Comment by ixjlyons** [comment]
Check the banner comment at the top of the Makefile (`head Makefile`). If it shows you're using Qt 4.x.x, make sure you have Qt5 installed and you are using qmake-qt5 to generate the Makefile,

**Comment by LeLobster** [comment]
In case anyone comes by here while trying to build twmn and runs into the same error (like I did earlier)

```
export QT_SELECT="qt5"
qmake
cd twmnd/ && qmake && cd ..
make
```

worked for me on Debian 9

**Comment by Penguin-Guru** [comment]
Seems like this could be closed?
